// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Order.DataAccess;

#nullable disable

namespace Order.DataAccess.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Order.Entity.Model.OrderDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Order.Entity.Model.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerGSM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Order.Entity.Model.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65b323ad-5ef6-4c34-8f40-d0a9baee42a2"),
                            Category = "Outdoors",
                            CreateDate = new DateTime(2022, 3, 30, 1, 45, 59, 342, DateTimeKind.Unspecified).AddTicks(9926),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Status = 1,
                            Unit = 60,
                            UnitPrice = 51f,
                            UpdateDate = new DateTime(2021, 6, 16, 7, 58, 8, 188, DateTimeKind.Unspecified).AddTicks(6973)
                        },
                        new
                        {
                            Id = new Guid("67386e5b-5b6f-4144-bcb0-19a1441a4772"),
                            Category = "Music",
                            CreateDate = new DateTime(2021, 11, 16, 10, 26, 53, 234, DateTimeKind.Unspecified).AddTicks(4963),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Status = 1,
                            Unit = 17,
                            UnitPrice = 57f,
                            UpdateDate = new DateTime(2021, 7, 24, 0, 36, 41, 388, DateTimeKind.Unspecified).AddTicks(4418)
                        },
                        new
                        {
                            Id = new Guid("606fbda4-7b38-4b6a-a2a6-5bc25085ba51"),
                            Category = "Jewelery",
                            CreateDate = new DateTime(2021, 5, 21, 16, 18, 57, 50, DateTimeKind.Unspecified).AddTicks(7873),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Status = 1,
                            Unit = 39,
                            UnitPrice = 52f,
                            UpdateDate = new DateTime(2022, 2, 14, 23, 29, 23, 875, DateTimeKind.Unspecified).AddTicks(7749)
                        },
                        new
                        {
                            Id = new Guid("f96ca098-80e7-4c80-9f0b-305729bf29cb"),
                            Category = "Sports",
                            CreateDate = new DateTime(2022, 2, 9, 9, 29, 44, 551, DateTimeKind.Unspecified).AddTicks(8042),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Status = 1,
                            Unit = 7,
                            UnitPrice = 52f,
                            UpdateDate = new DateTime(2022, 2, 9, 23, 15, 34, 680, DateTimeKind.Unspecified).AddTicks(4225)
                        },
                        new
                        {
                            Id = new Guid("5cd4200a-299e-4965-844c-ff3c936295ba"),
                            Category = "Sports",
                            CreateDate = new DateTime(2021, 5, 29, 19, 32, 50, 473, DateTimeKind.Unspecified).AddTicks(239),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Status = 1,
                            Unit = 26,
                            UnitPrice = 54f,
                            UpdateDate = new DateTime(2022, 4, 3, 20, 38, 50, 201, DateTimeKind.Unspecified).AddTicks(7839)
                        },
                        new
                        {
                            Id = new Guid("49f08698-0927-443f-aba1-2582a322b1f1"),
                            Category = "Garden",
                            CreateDate = new DateTime(2021, 10, 10, 11, 39, 47, 423, DateTimeKind.Unspecified).AddTicks(8685),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Status = 0,
                            Unit = 29,
                            UnitPrice = 57f,
                            UpdateDate = new DateTime(2021, 5, 23, 22, 47, 20, 838, DateTimeKind.Unspecified).AddTicks(5915)
                        },
                        new
                        {
                            Id = new Guid("b203b2d1-be33-445c-8568-3e03d1499fc9"),
                            Category = "Garden",
                            CreateDate = new DateTime(2021, 6, 29, 7, 49, 42, 156, DateTimeKind.Unspecified).AddTicks(3959),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Status = 1,
                            Unit = 6,
                            UnitPrice = 53f,
                            UpdateDate = new DateTime(2022, 2, 23, 15, 26, 29, 230, DateTimeKind.Unspecified).AddTicks(9036)
                        },
                        new
                        {
                            Id = new Guid("6751eecc-9bd3-4f52-929e-6c8cf1f15015"),
                            Category = "Industrial",
                            CreateDate = new DateTime(2022, 4, 9, 23, 20, 23, 117, DateTimeKind.Unspecified).AddTicks(808),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Status = 1,
                            Unit = 50,
                            UnitPrice = 57f,
                            UpdateDate = new DateTime(2022, 1, 3, 20, 49, 12, 921, DateTimeKind.Unspecified).AddTicks(5612)
                        },
                        new
                        {
                            Id = new Guid("56fe82f0-093b-492b-aec8-221eb7018baa"),
                            Category = "Beauty",
                            CreateDate = new DateTime(2021, 10, 23, 23, 20, 15, 936, DateTimeKind.Unspecified).AddTicks(7791),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Status = 1,
                            Unit = 46,
                            UnitPrice = 55f,
                            UpdateDate = new DateTime(2022, 2, 15, 4, 11, 7, 544, DateTimeKind.Unspecified).AddTicks(816)
                        },
                        new
                        {
                            Id = new Guid("ae60db97-fecf-4384-aada-a18c9afe1972"),
                            Category = "Shoes",
                            CreateDate = new DateTime(2021, 10, 9, 13, 36, 3, 942, DateTimeKind.Unspecified).AddTicks(9219),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Status = 1,
                            Unit = 55,
                            UnitPrice = 51f,
                            UpdateDate = new DateTime(2021, 9, 12, 19, 24, 52, 653, DateTimeKind.Unspecified).AddTicks(1035)
                        },
                        new
                        {
                            Id = new Guid("3718c9c1-fd05-4e9b-a23b-639ae211a1df"),
                            Category = "Home",
                            CreateDate = new DateTime(2021, 7, 11, 6, 4, 8, 361, DateTimeKind.Unspecified).AddTicks(499),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Status = 1,
                            Unit = 41,
                            UnitPrice = 52f,
                            UpdateDate = new DateTime(2022, 4, 21, 22, 34, 3, 153, DateTimeKind.Unspecified).AddTicks(915)
                        },
                        new
                        {
                            Id = new Guid("92129ae8-c9da-410c-b649-9443eac9fa4c"),
                            Category = "Outdoors",
                            CreateDate = new DateTime(2021, 5, 15, 22, 56, 18, 346, DateTimeKind.Unspecified).AddTicks(6215),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Status = 1,
                            Unit = 55,
                            UnitPrice = 57f,
                            UpdateDate = new DateTime(2021, 7, 31, 16, 44, 48, 399, DateTimeKind.Unspecified).AddTicks(1478)
                        },
                        new
                        {
                            Id = new Guid("945662ea-de15-4a58-9924-bb696f7c2be2"),
                            Category = "Clothing",
                            CreateDate = new DateTime(2021, 11, 24, 3, 43, 33, 275, DateTimeKind.Unspecified).AddTicks(5539),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Status = 1,
                            Unit = 32,
                            UnitPrice = 54f,
                            UpdateDate = new DateTime(2021, 7, 28, 0, 15, 0, 352, DateTimeKind.Unspecified).AddTicks(2)
                        },
                        new
                        {
                            Id = new Guid("71efc825-1083-4cc4-b5e2-0cc05361c337"),
                            Category = "Shoes",
                            CreateDate = new DateTime(2021, 7, 4, 0, 42, 56, 549, DateTimeKind.Unspecified).AddTicks(2633),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Status = 0,
                            Unit = 32,
                            UnitPrice = 50f,
                            UpdateDate = new DateTime(2021, 11, 4, 23, 41, 29, 991, DateTimeKind.Unspecified).AddTicks(2597)
                        },
                        new
                        {
                            Id = new Guid("cf13f1b4-f6c8-43ea-bb20-3a965c5cf8c6"),
                            Category = "Electronics",
                            CreateDate = new DateTime(2022, 2, 25, 18, 40, 37, 11, DateTimeKind.Unspecified).AddTicks(9957),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Status = 1,
                            Unit = 72,
                            UnitPrice = 56f,
                            UpdateDate = new DateTime(2022, 1, 19, 6, 13, 23, 617, DateTimeKind.Unspecified).AddTicks(7847)
                        },
                        new
                        {
                            Id = new Guid("3a8d27bb-6600-4a7c-a190-2dc9ea014f6d"),
                            Category = "Jewelery",
                            CreateDate = new DateTime(2022, 4, 17, 14, 4, 14, 102, DateTimeKind.Unspecified).AddTicks(2240),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Status = 0,
                            Unit = 16,
                            UnitPrice = 57f,
                            UpdateDate = new DateTime(2021, 6, 23, 6, 39, 31, 525, DateTimeKind.Unspecified).AddTicks(9496)
                        },
                        new
                        {
                            Id = new Guid("f61e863e-7da1-4fa6-bd96-9fb4a51970c5"),
                            Category = "Health",
                            CreateDate = new DateTime(2021, 10, 17, 0, 45, 3, 924, DateTimeKind.Unspecified).AddTicks(9849),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Status = 0,
                            Unit = 75,
                            UnitPrice = 51f,
                            UpdateDate = new DateTime(2021, 8, 10, 9, 53, 29, 216, DateTimeKind.Unspecified).AddTicks(4255)
                        },
                        new
                        {
                            Id = new Guid("a25d0072-230f-4e61-8fa2-e1684eb47e4e"),
                            Category = "Health",
                            CreateDate = new DateTime(2021, 12, 12, 20, 16, 3, 303, DateTimeKind.Unspecified).AddTicks(5983),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Status = 0,
                            Unit = 93,
                            UnitPrice = 55f,
                            UpdateDate = new DateTime(2021, 8, 4, 5, 19, 11, 951, DateTimeKind.Unspecified).AddTicks(7064)
                        },
                        new
                        {
                            Id = new Guid("81c19555-9474-4cb5-b79e-8b8fad63e4ae"),
                            Category = "Outdoors",
                            CreateDate = new DateTime(2021, 9, 25, 18, 38, 24, 911, DateTimeKind.Unspecified).AddTicks(2185),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Status = 1,
                            Unit = 16,
                            UnitPrice = 54f,
                            UpdateDate = new DateTime(2021, 8, 24, 10, 51, 50, 365, DateTimeKind.Unspecified).AddTicks(8642)
                        });
                });

            modelBuilder.Entity("Order.Entity.Model.OrderDetailEntity", b =>
                {
                    b.HasOne("Order.Entity.Model.OrderEntity", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Order.Entity.Model.ProductEntity", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Order.Entity.Model.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Order.Entity.Model.ProductEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
